### ISSUE TITLE
Elucidate path to travis via rm large data in tests

### ISSUE THREAD

**Issue by bc** [bc/frontiers2017#39]

**Comment by bc** [comment]
Failed -------------------------------------------------------------------------
- [ ] 1. Error: produce A matrices for different numbers of muscles or output force dimensions (@test_a_matrix.r#15) 
cannot open file '../../output/a_mat_fit.pdf'
1: pdf("../../output/a_mat_fit.pdf") at /home/travis/build/bc/frontiers2017/tests/testthat/test_a_matrix.r:15
- [ ] 2. Error: we can produce binary set of vectors for use with cadaver or robotic 7-muscle systems (@test_a_matrix.r#46) 
cannot open the connection
1: write_binary_combination_csv(7, c(3.12, 10.0001), "../../output/map_unit_cube.csv") at /home/travis/build/bc/frontiers2017/tests/testthat/test_a_matrix.r:46
2: write.csv(df, filename, row.names = FALSE, quote = FALSE) at /home/travis/build/bc/frontiers2017/R/a_matrix.r:302
3: eval.parent(Call)
4: eval(expr, p)
5: eval(expr, p)
6: write.table(df, filename, row.names = FALSE, quote = FALSE, col.names = TRUE, sep = ",", 
       dec = ".", qmethod = "double")
7: file(file, ifelse(append, "a", "w"))
- [ ] 3. Error: can produce new har CSV from 0,1 CSV (@test_a_matrix.r#103) ----------
File is empty: /dev/shm/file54b93194b2ef
1: fread("/Users/briancohn/Resilio Sync/data/noPostureNeutralForceTrials2017_11_12_14_28_20.txt") at /home/travis/build/bc/frontiers2017/tests/testthat/test_a_matrix.r:103
- [ ] 4. Error: Show a sample snapshot of the data collected (@test_data_description.r#13) 
cannot open the connection
1: save_snapshot_for_first_posture(first_data_chunk, output_filepath) at /home/travis/build/bc/frontiers2017/tests/testthat/test_data_description.r:13
2: write.csv(first_posture_data, output_filepath, row.names = FALSE) at /home/travis/build/bc/frontiers2017/R/functions_specific_to_frontiers2017_dataset.r:6
3: eval.parent(Call)
4: eval(expr, p)
5: eval(expr, p)
6: write.table(first_posture_data, output_filepath, row.names = FALSE, col.names = TRUE, 
       sep = ",", dec = ".", qmethod = "double")
7: file(file, ifelse(append, "a", "w"))
- [x] 5. Error: we can produce viable noise csv with correct number of replicates etc (@test_force_vector_replicability.r#8) 
object 'muscle_of_interest' not found
1: noise_df(muscles_of_interest, num_maps, tension_range) at /home/travis/build/bc/frontiers2017/tests/testthat/test_force_vector_replicability.r:8
2: uar_matrix(number_of_maps_to_generate, length(muscle_of_interest), min = muscle_range[1], 
       max = muscle_range[2]) at /home/travis/build/bc/frontiers2017/R/force_vector_replicability.r:13
3: matrix(runif(rows * cols, min = min, max = max), ncol = cols) at /home/travis/build/bc/frontiers2017/R/force_vector_replicability.r:6
4: runif(rows * cols, min = min, max = max)
- [ ] 6. Error: df_to_max_signed_residual gets the correct ranges (@test_ForceTrial.r#5) 
argument is of length zero
1: readRDS(all_file_paths("~/Resilio Sync/data/ForceTrials_at_each_posture/")[1]) at /home/travis/build/bc/frontiers2017/tests/testthat/test_ForceTrial.r:5
2: all_file_paths("~/Resilio Sync/data/ForceTrials_at_each_posture/")
3: simplify2array(lapply(dir(pwd_of_directory), prepend_string, pwd_of_directory)) at /home/travis/build/bc/frontiers2017/R/generic_tools.r:110
- [ ] 7. Failure: get resilio filepath creates correct path (@test_generic_tools.r#46) 
file.exists(filepath) isn't true.

**Comment by bc** [comment]
5cec789f6eaee9d80701e7546df90f92a3fa1c5b in order to make travis run faster

**Comment by bc** [comment]
- [x] get entire nov script to run through and through with no errors or sideeffects.
- [ ] ensure the first task maps all create the desired task when multiplied by the big_A matrix.
- [ ] analyze how close the first task maps match the desired map

**Comment by bc** [comment]
![image](https://user-images.githubusercontent.com/13772726/33039400-acbaf36a-cdec-11e7-8a71-592caca56f81.png)
Task maps do not match desired task when multiplied by big_A matrix.
Now focusing on extricating and testing har matrix generation functions

**Comment by bc** [comment]
Apply native bindings for lb and ub constraints:
- [x] with sample arm example
- [x] ‘lowerBoundConstraint’ encodes w_i >= x
- [x]   ‘upperBoundConstraint’ encodes w_i <= x
- [x] with real data

**Comment by bc** [comment]
![image](https://user-images.githubusercontent.com/13772726/33041260-9742ed2a-cdf2-11e7-8ced-60df3e3c8d79.png)
constraints have to be instantiated separately:
![image](https://user-images.githubusercontent.com/13772726/33041277-a315c0dc-cdf2-11e7-9819-f57e02a9cb74.png)

**Comment by bc** [comment]
![image](https://user-images.githubusercontent.com/13772726/33041391-04a8e234-cdf3-11e7-8c1f-78d175f245b2.png)
Seems to work with equality motor constraints

**Comment by bc** [comment]
![image](https://user-images.githubusercontent.com/13772726/33042371-76d92d20-cdf6-11e7-83e4-d47809b59f6b.png)
Working via create_bound_constraints instead of manually generating bound matrices

**Comment by bc** [comment]
works with different tasks
![image](https://user-images.githubusercontent.com/13772726/33043297-d0acddd0-cdf9-11e7-8168-666c2de73ed3.png)

**Comment by bc** [comment]
![image](https://user-images.githubusercontent.com/13772726/33044876-8832b682-cdff-11e7-9472-9ec257ff7f86.png)
Working with one task force with real data

**Comment by bc** [comment]
- [x] with multiple tasks

**Comment by bc** [comment]
[fdsa.pdf](https://github.com/bc/frontiers2017/files/1489420/fdsa.pdf)

**Comment by bc** [comment]
Works with hi and low point num
![image](https://user-images.githubusercontent.com/13772726/33046079-4bb906e8-ce04-11e7-9193-01d202968235.png)
