### ISSUE TITLE
Clear data loading path errors

### ISSUE THREAD

**Issue by bc** [bc/frontiers2017#63]
Failed -------------------------------------------------------------------------
- [ ] 1. Error: 1A looks good, create new activations for 1A and decide on task for 2A (@test_extensormechanism2017_cadaver.r#39)
File is empty: /var/folders/vj/57777k0931s8txw12189jmhh0000gn/T//RtmpbSj44v/filecc8f9e38cc
1: as.data.frame(fread(get_Resilio_filepath(noise_response_filename))) at /Users/briancohn/Documents/GitHub/bc/frontiers2017/tests/testthat/test_extensormechanism2017_cadaver.r:39
2: fread(get_Resilio_filepath(noise_response_filename))

- [ ] 2. Error: 2A looks good (@test_extensormechanism2017_cadaver.r#204) ------------
File is empty: /var/folders/vj/57777k0931s8txw12189jmhh0000gn/T//RtmpbSj44v/filecc85ca2e116
1: as.data.frame(fread(get_Resilio_filepath(filename_2A))) at /Users/briancohn/Documents/GitHub/bc/frontiers2017/tests/testthat/test_extensormechanism2017_cadaver.r:204
2: fread(get_Resilio_filepath(filename_2A))

- [ ] 3. Error: 3A looks good (@test_extensormechanism2017_cadaver.r#359) ------------
File is empty: /var/folders/vj/57777k0931s8txw12189jmhh0000gn/T//RtmpbSj44v/filecc849679add
1: as.data.frame(fread(get_Resilio_filepath(filename_3A))) at /Users/briancohn/Documents/GitHub/bc/frontiers2017/tests/testthat/test_extensormechanism2017_cadaver.r:359
2: fread(get_Resilio_filepath(filename_3A))

- [x] 4. Error: 4A looks good (@test_extensormechanism2017_cadaver.r#515) ------------
File is empty: /var/folders/vj/57777k0931s8txw12189jmhh0000gn/T//RtmpbSj44v/filecc830e848d1
1: as.data.frame(fread(get_Resilio_filepath(filename_4A))) at /Users/briancohn/Documents/GitHub/bc/frontiers2017/tests/testthat/test_extensormechanism2017_cadaver.r:515
2: fread(get_Resilio_filepath(filename_4A))

- [x] 5. Error: we can produce a FFS vertex series of points to plug into the hand. use different levels so we can evaluate how linear the scaling is for each vertex direction is. (@test_FFS_scaling.R#19)
object 'muscles_of_interest' not found
1: .handleSimpleError(function (e)
   { at /Users/briancohn/Documents/GitHub/bc/frontiers2017/tests/testthat/test_FFS_scaling.R:19
2: eval(code, test_env)

- [x] 6. Error: when we get noise through the MIT hand (500 forces, 1 replicate), I can make an A matrix (@test_mit_hand_precadaver.r#144)
object 'timeseries_tendons_to_posts' not found
1: ggplot(tail(timeseries_tendons_to_posts, 100)) at /Users/briancohn/Documents/GitHub/bc/frontiers2017/tests/testthat/test_mit_hand_precadaver.r:144
2: tail(timeseries_tendons_to_posts, 100)

- [x] 7. Error: evaluate different threshlds for 0-torque requirements (@test_mit_hand_precadaver.r#182)
object 'A_fit' not found
1: multiple_tasks_to_sset(A_fit$AMatrix, task_df, thin = 100, torque_max_deviation = 0.01,
       num_samples_desired = num_samples_desired) at /Users/briancohn/Documents/GitHub/bc/frontiers2017/tests/testthat/test_mit_hand_precadaver.r:182
2: lapply(df_to_list_of_rows(task_df), function(task_i) {
       samples <- constraints_inc_torque_to_points(muscle_column_generators = t(AMatrix),  at /Users/briancohn/Documents/GitHub/bc/frontiers2017/R/mit_hand_precadaver.r:103
3: FUN(X[[i]], ...)
4: constraints_inc_torque_to_points(muscle_column_generators = t(AMatrix), range_tension = range_tension,
       task_i, num_samples_desired = num_samples_desired, thin = thin, torque_max_deviation = torque_max_deviation) at /Users/briancohn/Documents/GitHub/bc/frontiers2017/R/mit_hand_precadaver.r:104
5: ncol(muscle_column_generators) at /Users/briancohn/Documents/GitHub/bc/frontiers2017/R/hitandrun.r:132
6: t(AMatrix)
